
*********************************************************************************************
*																							*
* 	Read in the files, and associated file paths, for each document							*
*																							*
*********************************************************************************************;
	filename indata pipe 'dir C:\EnterpriseMiner\source /b';	/* Specify the filepath "pipe" where the files are located					*/
	data files;
		infile indata truncover;
		input f2r $200.;										/* The filename is restricted to 200 characters, but this can be changed.	*/
		filepaths = 'C:\EnterpriseMiner\source\' || f2r;		/* The filepath is concatenated with the filename.							*/
		drop f2r;
		run;

/*
data a;
text='C:\Users\dazara\Desktop\misc\SAS_TESTDATA.txt'; output;
run;
*/

*********************************************************************************************
*																							*
* 	Parse the document collection. This code will generate two SAS datasets: Key and Out	*
*																							*
*********************************************************************************************;
	proc tgparse data=files
		key=key	
		config=config	
		ignore=sashelp.stoplst
		entities=YES
		noungroups=MAX
		tagging=YES
		outoffset=offset
		stemming=YES
		out=out
		namedfile;
		var filepaths;
		run;
		quit;


*********************************************************************************************
*																							*
* 	Configuration (optional) Variables														*
*																							*
*********************************************************************************************

CONFIG			Specifies the SAS data set containing configuration information. If this option is
				specified, the file might or might not exist. If the file does not exist, PROC
				DOCPARSE creates the file and fills in the columns as specified in the PROC
				DOCPARSE statement
DATA			Specifies the SAS data set that contains the documents or the file references to parse.
				If you omit the DATA= option, the procedure uses the value of the _LAST_= SAS
				system option. The default of _LAST_= is the most recently created SAS data set in
				the current SAS job or session
DOC_ID			Specifies the starting _DOCUMENT_ number in the OUT data set. Use this option
				to perform iterative parsing. See the OUT= option for a detailed description of the
				contents of the OUT data set
ENCODING		UTF-8 or ASCII
ENTITIES		Specifies whether to find entities. See the SELECT statement for refining the entity
				search
ENTLIST			A string that contains space-delimited entities to keep in parsing
IGNORE			Specifies the SAS data set that contains the terms to ignore. An example data set
				that contains an ignore list can be found in the Sashelp library. It is called
				STOPLST. Ignore lists and stop lists have the same format
INKEY			Specifies a SAS data set that was previously generated by PROC DOCPARSE. Use
				this option to perform iterative parsing. This data set is the starting point when
				processing the KEY= data set
KEY				Specifies one of the SAS data sets that is produced by PROC DOCPARSE. This data
				set contains a frequency table of the term by document
LANGUAGE		Use the following quoted strings: "danish", "dutch", "english", "finnish",
				"french", "german", "italian", "japanese", "korean", "bokmal",
				"portuguese", "simplified-chinese", "spanish", "swedish", and
				"traditional-chinese".
NOUNGROUPS		If noun group processing is turned off, the value is OFF. If
				noun group processing is turned on, the value is set to
				either MAX, SUB, or STD. See the NOUNGROUP option for details
NAMEDFILE		Y if the VAR statement specifies a column in an external file 
				that contains the text to parse. N if the VAR statement specifies 
				a column that contains the text to parse.
NOPOS			Omits the search for any parts of speech. Use this option when you want to invoke
				the NOUNGROUP or ENTITY finder only
OUT				Specifies one of the SAS data sets that is produced by PROC DOCPARSE. This data
				set contains information about the terms
OUTOFFSET		Specifies an output SAS data set that contains offset and length information for a
				particular term
RETAIN			Specifies the SAS data set that contains the terms to retain. Retain lists and ignore
				lists have the same format
START			Specifies the SAS data set that contains the terms to include in your analysis. For
				items in the START list, the KEEP variable has a value of Y.
STEMMING		If stemming is turned on, the value is Y. If stemming is not
				turned on, the value is N
STOP			Specifies the SAS data set that contains the terms to exclude in your analysis. The
				terms are displayed in the KEY data set. They are not included as parents or rolled
				up into their respective parent. For items in the STOP list, the KEEP variable has a
				value of N. See the STOPLST data set in the Sashelp library for an example. Ignore
				lists and stop lists have the same format
SYN				Specifies the SAS data set that contains parent-child relationships. The data set
				must have the following variables: TERM, PARENT, and CATEGORY. Alternatively,
				the data set can have the following variables: TERM, PARENT, TERMROLE, and
				PARENTROLE. This option can be used with or without stemming. If stemming is
				turned on, then the synonym list overrides any parent-child relationship specified by
				the natural language processor. If stemming is turned off, the synonym list is used
				and the parent-child relationships are generated in the KEY data set. No other
				parent-child relationship, other than the ones specified in the synonym list data set,
				is generated
TAGGING			If tagging is turned on, the value is Y. If tagging is not
				turned on, the value is N
;
		
*ZEND;
